### ISSUE TITLE
This looks like a conflict with jquery.lazyload.min.js.

### ISSUE THREAD

**Issue by AlliotTech** [theme-next/theme-next-fancybox3#2]
I have used lazyload on my blog. When I click a picture, the fancybox shows the loading.png.
 https://www.npmjs.com/package/hexo-lazyload-image/v/1.0.3
![image](https://user-images.githubusercontent.com/24980252/46567109-37338700-c95f-11e8-807e-20b6a2e09461.png)

**Comment by ivan-nginx** [comment]
Try this: https://github.com/theme-next/theme-next-jquery-lazyload
