### ISSUE TITLE
Uncaught TypeError: $(...).fancybox is not a function

### ISSUE THREAD

**Issue by hourglass1016** [theme-next/theme-next-fancybox3#3]
![image](https://user-images.githubusercontent.com/22876293/49204175-ef246400-f3e5-11e8-890e-436da2881c8d.png)
![image](https://user-images.githubusercontent.com/22876293/49204240-2eeb4b80-f3e6-11e8-9c8c-cd2bdac39dd1.png)

In Hexo Next6 Theme I make fancybox config  is true，and in my blog I have add jquery at the first of fancybox.js，but it's turn wrong!

**Comment by maple3142** [comment]
Please take the comment above it a look, have you install it through cloning fancybox 2 or 3?

**Comment by hourglass1016** [comment]
![image](https://user-images.githubusercontent.com/22876293/49262555-ed0fe300-f481-11e8-8e26-1e01d4c56041.png)
Yes，I used Hexo's own, and then I downloaded fancybox3 and replace it

**Comment by ivan-nginx** [comment]
Try to remove APlayer. Working on clean install?

**Comment by hourglass1016** [comment]
OK！Thanks!

**Comment by ivan-nginx** [comment]
So? Issue was solved?
