### ISSUE TITLE
Bug in Fancybox 3: missing arrow right / left

### ISSUE THREAD

**Issue by online** [theme-next/theme-next-fancybox3#4]
Hello.

Something obviously broke.

![fancybox_2019-03-17_000647](https://user-images.githubusercontent.com/722881/54482214-eea2c280-4848-11e9-979c-8e2ea63f2698.png)

**Comment by ivan-nginx** [comment]
@stevenjoezhang this bug appear after your last update. Recheck it.

**Comment by stevenjoezhang** [comment]
![屏幕快照 2019-03-17 上午8 51 56](https://user-images.githubusercontent.com/16272760/54483660-fdfa2e00-4891-11e9-8457-cae62e86774d.png)
Can't reproduce.
Besides, have you edited source code of NexT? This button (share) should not display here.
![54482214-eea2c280-4848-11e9-979c-8e2ea63f2698](https://user-images.githubusercontent.com/16272760/54483672-28e48200-4892-11e9-8d1b-5cfb5eb8fce0.png)
Unless you have changed the configuration of fancybox:
https://github.com/theme-next/hexo-theme-next/blob/ce75c7ec396fb7355017dd6d55f8d9cb9da667aa/source/js/src/utils.js#L38-L46

**Comment by ivan-nginx** [comment]
@stevenjoezhang can u try to `hexo g` instead of `hexo s`? Sometimes server work, but generated files in remote server not.

> Besides, have you edited source code of NexT? This button (share) SHOULD NOT display here.

He's download clean NexT version, switched between v7.0.0 and v7.0.1 tags. After that we decide to check fancybox3 module and, when he reset master to previous commit — it all worked.

P.S. He's my friend.

**Comment by stevenjoezhang** [comment]
I know, but the share button should not be displayed in clean NexT version. Would you like to confirm again that the settings of fancybox is not changed?
See: https://fancyapps.com/fancybox/3/docs/#options
`button: ["share"]` is not enabled by default, and I can't reproduce that

**Comment by ivan-nginx** [comment]
Ok, lets do it simple? Let's add on official site something like demo with group images and fancybox3? It will be demo and, in the same time, tests.

***

In ideal we must have subdomain for tests. But I'm not sure it necessary.

**Comment by online** [comment]
@stevenjoezhang, in NexT theme folder I just edit only one file — config. I changed `false` —> `true` to activate fancybox + download latest version of Fancybox 3 in `next/source/lib/fancybox`.

**Comment by stevenjoezhang** [comment]
@online That's really weird... would you like to publish the page, and provide the URL to debug?

**Comment by ivan-nginx** [comment]
> Ok, lets do it simple? Let's add on official site something like demo with group images and fancybox3? It will be demo and, in the same time, tests.

What are u talknig about. guys? Just add fancybox 3 with gallery and we will see what happening.

P.S. I switched versions temporarily, so during generate need just switch branch for plugin.

**Comment by online** [comment]
@stevenjoezhang, of course, here you are:

https://inotes.pp.ua/2019/01/10/git-cheat-sheet/

**Comment by ivan-nginx** [comment]
@online try now reinstall plugin. Must work previous version 3.2.5. Is that true?

@stevenjoezhang can u create docs with gallery usage [here](https://theme-next.org/docs/tag-plugins/group-pictures/)? Like live demo, like all other tags. And I'll add fancybox into the script. And we will check this bug.

**Comment by online** [comment]
@ivan-nginx, I don't have access to the computer now. I will check in the evening.

**Comment by stevenjoezhang** [comment]
@online The css is malformed in v3.2.5... 
![屏幕快照 2019-03-17 下午5 03 13](https://user-images.githubusercontent.com/16272760/54487970-1ccee380-48d7-11e9-8338-6936e3202fdb.png)
![屏幕快照 2019-03-17 下午5 03 25](https://user-images.githubusercontent.com/16272760/54487971-1d677a00-48d7-11e9-96b5-4d885953117c.png)
![屏幕快照 2019-03-17 下午5 02 47](https://user-images.githubusercontent.com/16272760/54487973-1e98a700-48d7-11e9-9bb9-adbdfff85b57.png)
I'll push the newest version to the `dev` branch of this repo. If everything is fine, I'll make it the master branch

**Comment by stevenjoezhang** [comment]
@ivan-nginx @online I found the reason, now the master branch should be fine.

**Comment by online** [comment]
@stevenjoezhang, everything is working fine in the latest v. 3.5.7 👍
